#!/usr/bin/env sh
# Generated from sketchybar-app-font's APPM metadata.
case "$1" in
  Live ) printf %s :ableton: ;;
  'Accessibility Reader' ) printf %s :accessibility_reader: ;;
  Acrobat ) printf %s :acrobat: ;;
  'Activity Monitor'|'Aktivitätsanzeige'|'Монітор активності'|'Монитор активности' ) printf %s :activity_monitor: ;;
  aw-tauri ) printf %s :activitywatch: ;;
  Actual ) printf %s :actual: ;;
  'AdGuard VPN' ) printf %s :adguard_vpn: ;;
  'Adobe Bridge'*'' ) printf %s :adobe_bridge: ;;
  AFFiNE ) printf %s :affine: ;;
  Affinity ) printf %s :affinity: ;;
  'Affinity Designer' ) printf %s :affinity_designer: ;;
  'Affinity Designer 2' ) printf %s :affinity_designer_2: ;;
  'Affinity Photo' ) printf %s :affinity_photo: ;;
  'Affinity Photo 2' ) printf %s :affinity_photo_2: ;;
  'Affinity Publisher' ) printf %s :affinity_publisher: ;;
  'Affinity Publisher 2' ) printf %s :affinity_publisher_2: ;;
  Airmail ) printf %s :airmail: ;;
  'AirPort Utility' ) printf %s :airport_utility: ;;
  AirVPN|Eddie ) printf %s :airvpn: ;;
  Alacritty ) printf %s :alacritty: ;;
  Alfred ) printf %s :alfred: ;;
  AltTab ) printf %s :alttab: ;;
  AmneziaVPN ) printf %s :amnezia_vpn: ;;
  BlueStacks|HD-MultiInstanceManager ) printf %s :android: ;;
  'Android Messages' ) printf %s :android_messages: ;;
  'Android Studio' ) printf %s :android_studio: ;;
  Anki ) printf %s :anki: ;;
  Antigravity|'Antigravity IDE' ) printf %s :antigravity: ;;
  AnyDesk ) printf %s :anydesk: ;;
  Anytype ) printf %s :anytype: ;;
  ApiArk ) printf %s :apiark: ;;
  Apifox ) printf %s :apifox: ;;
  'App Eraser' ) printf %s :app_eraser: ;;
  'App Store' ) printf %s :app_store: ;;
  'Apple Books'|Books|'Bücher' ) printf %s :apple_books: ;;
  'Apple Configurator' ) printf %s :apple_configurator: ;;
  TV ) printf %s :apple_tv: ;;
  Arc ) printf %s :arc: ;;
  Arduino|'Arduino IDE' ) printf %s :arduino: ;;
  Aseprite ) printf %s :aseprite: ;;
  Aside ) printf %s :aside: ;;
  Atom ) printf %s :atom: ;;
  Audacity ) printf %s :audacity: ;;
  'Audio MIDI Setup' ) printf %s :audio_midi_setup: ;;
  AusweisApp ) printf %s :ausweisapp: ;;
  Automator ) printf %s :automator: ;;
  Azahar ) printf %s :azahar: ;;
  Backblaze|'Backblaze Downloader'|'Backblaze Restore' ) printf %s :backblaze: ;;
  BaiduNetdisk|'百度网盘' ) printf %s :baidunetdisk: ;;
  balenaEtcher ) printf %s :balena_etcher: ;;
  'Bambu Studio' ) printf %s :bambu_studio: ;;
  MoneyMoney ) printf %s :bank: ;;
  Basecamp|Basecamp.app ) printf %s :basecamp: ;;
  Battle.net ) printf %s :battle_net: ;;
  Bazaar ) printf %s :bazaar: ;;
  Bazecor ) printf %s :bazecor: ;;
  BBEdit ) printf %s :bbedit: ;;
  Bear ) printf %s :bear: ;;
  'Beekeeper Studio' ) printf %s :beekeeper_studio: ;;
  Beeper|'Beeper Desktop' ) printf %s :beeper: ;;
  Betterbird ) printf %s :betterbird: ;;
  BetterTouchTool ) printf %s :bettertouchtool: ;;
  Bilibili|'哔哩哔哩' ) printf %s :bilibili: ;;
  Bionic ) printf %s :bionic: ;;
  Bitwarden ) printf %s :bit_warden: ;;
  'Bitwig Studio' ) printf %s :bitwig_studio: ;;
  Blender ) printf %s :blender: ;;
  Blitzit ) printf %s :blitzit: ;;
  Bluesky|Sky ) printf %s :bluesky: ;;
  'Bluetooth File Exchange'|Bluetooth ) printf %s :bluetooth: ;;
  'BluOS Controller' ) printf %s :bluos_controller: ;;
  Calibre|'Книги' ) printf %s :book: ;;
  YABA|Anybox|'URL Manager Pro' ) printf %s :bookmark: ;;
  Brain.fm ) printf %s :brainfm: ;;
  'Brave Browser' ) printf %s :brave_browser: ;;
  Broadcasts ) printf %s :broadcasts: ;;
  Bruno ) printf %s :bruno: ;;
  Burn ) printf %s :burn: ;;
  'Burp Suite'*'' ) printf %s :burp_suite: ;;
  BusyCal ) printf %s :busycal: ;;
  Buzz ) printf %s :buzz: ;;
  Calculator|Calculette|Rechner|'Калькулятор' ) printf %s :calculator: ;;
  Calendar|'日历'|Fantastical|Cron|Amie|Calendrier|'カレンダー'|'Notion Calendar'|Kalender|'Календар'|'Календарь' ) printf %s :calendar: ;;
  calibre ) printf %s :calibre: ;;
  Capacities ) printf %s :capacities: ;;
  Caprine ) printf %s :caprine: ;;
  'Carbon Copy Cloner' ) printf %s :carbon_copy_cloner: ;;
  'ChatGPT Atlas' ) printf %s :chatgpt_atlas: ;;
  'Cherry Studio' ) printf %s :cherry_studio: ;;
  Chess|'The Enemy Within' ) printf %s :chess: ;;
  'Amazon Chime' ) printf %s :chime: ;;
  Choosy ) printf %s :choosy: ;;
  'Cisco AnyConnect Secure Mobility Client'|'Cisco Secure Client' ) printf %s :cisco_anyconnect: ;;
  Citra ) printf %s :citra: ;;
  'Citrix Workspace'|'Citrix Viewer' ) printf %s :citrix: ;;
  ClassIn ) printf %s :classin: ;;
  Claude ) printf %s :claude: ;;
  ClickUp ) printf %s :click_up: ;;
  CLion ) printf %s :clion: ;;
  Clock ) printf %s :clock: ;;
  cmux|'cmux NIGHTLY' ) printf %s :cmux: ;;
  coconutBattery ) printf %s :coconut_battery: ;;
  Code|'Code - Insiders' ) printf %s :code: ;;
  Codex ) printf %s :codex: ;;
  'Cold Turkey Blocker' ) printf %s :cold_turkey_blocker: ;;
  'Color Picker'|'数码测色计'|'Кольоромір'|'Цифровой колориметр'|'Digital Color Meter' ) printf %s :color_picker: ;;
  Comet ) printf %s :comet_browser: ;;
  Conductor ) printf %s :conductor: ;;
  Console ) printf %s :console: ;;
  Contacts ) printf %s :contacts: ;;
  Copilot ) printf %s :copilot: ;;
  CotEditor ) printf %s :coteditor: ;;
  Craft ) printf %s :craft: ;;
  'Creative Cloud' ) printf %s :creative_cloud: ;;
  CrossOver ) printf %s :crossover: ;;
  Cubase|'Cubase Pro' ) printf %s :cubase: ;;
  CurseForge ) printf %s :curseforge: ;;
  Cursor ) printf %s :cursor: ;;
  Cypress ) printf %s :cypress: ;;
  DaisyDisk ) printf %s :daisy_disk: ;;
  Dash ) printf %s :dash: ;;
  DataGrip ) printf %s :datagrip: ;;
  DataSpell ) printf %s :dataspell: ;;
  'DaVinci Resolve' ) printf %s :davinciresolve: ;;
  DBeaver ) printf %s :dbeaver: ;;
  DeepL ) printf %s :deepl: ;;
  DeepSeek ) printf %s :deepseek: ;;
  Deezer ) printf %s :deezer: ;;
  Default ) printf %s :default: ;;
  'Default Folder X' ) printf %s :default_folder_x: ;;
  Delta ) printf %s :delta: ;;
  Deluge ) printf %s :deluge: ;;
  deno ) printf %s :deno: ;;
  'CleanMyMac X' ) printf %s :desktop: ;;
  Devin ) printf %s :devin: ;;
  'DEVONthink 3'|DEVONthink ) printf %s :devonthink3: ;;
  Dexcom ) printf %s :dexcom: ;;
  Dia ) printf %s :dia: ;;
  Dictionary ) printf %s :dictionary: ;;
  DingTalk|'钉钉'|'阿里钉' ) printf %s :dingtalk: ;;
  Discord|'Discord Canary'|'Discord PTB' ) printf %s :discord: ;;
  'Disk Utility' ) printf %s :disk_utility: ;;
  Docker|'Docker Desktop' ) printf %s :docker: ;;
  GrandTotal|Receipts ) printf %s :dollar: ;;
  Dolphin ) printf %s :dolphin: ;;
  Dorico|'Dorico Pro' ) printf %s :dorico: ;;
  'Dota 2' ) printf %s :dota2: ;;
  'Double Commander' ) printf %s :doublecmd: ;;
  'Downie 4' ) printf %s :downie: ;;
  Drafts ) printf %s :drafts: ;;
  draw.io ) printf %s :draw_io: ;;
  Dropbox ) printf %s :dropbox: ;;
  Dropover ) printf %s :dropover: ;;
  DSM ) printf %s :dsm: ;;
  'DVD Player' ) printf %s :dvd_player: ;;
  'EA app' ) printf %s :ea: ;;
  Eagle ) printf %s :eagle: ;;
  Electron ) printf %s :electron: ;;
  Element ) printf %s :element: ;;
  Emacs ) printf %s :emacs: ;;
  'Epic Games Launcher' ) printf %s :epic_games: ;;
  EuDic ) printf %s :eudic: ;;
  'Evernote Legacy'|Evernote ) printf %s :evernote_legacy: ;;
  FaceTime|'FaceTime 通话' ) printf %s :face_time: ;;
  'Feedback Assistant' ) printf %s :feedback_assistant: ;;
  Feishu|'飞书'|'飞书会议' ) printf %s :feishu: ;;
  Figma ) printf %s :figma: ;;
  FileBot ) printf %s :filebot: ;;
  FileZilla ) printf %s :filezilla: ;;
  'Final Cut Pro' ) printf %s :final_cut_pro: ;;
  Finamp ) printf %s :finamp: ;;
  'Find My'|'Локатор' ) printf %s :find_my: ;;
  Finder|'访达'|Bloom|FlowFinder ) printf %s :finder: ;;
  Firefox ) printf %s :firefox: ;;
  'Firefox Developer Edition'|'Firefox Nightly' ) printf %s :firefox_developer_edition: ;;
  Flaresolverr ) printf %s :flaresolverr: ;;
  Floorp ) printf %s :floorp: ;;
  FlowJo ) printf %s :flowjo: ;;
  'FL Studio' ) printf %s :flstudio: ;;
  Fluxer ) printf %s :fluxer: ;;
  'FMOD Studio' ) printf %s :fmod: ;;
  Folx ) printf %s :folx: ;;
  'Font Book' ) printf %s :font_book: ;;
  foobar2000 ) printf %s :foobar2000: ;;
  Fork ) printf %s :fork: ;;
  ForkLift ) printf %s :forklift: ;;
  'Foxit PDF Reader' ) printf %s :foxit_reader: ;;
  FreeLLMAPI ) printf %s :free_llm_api: ;;
  FreeCAD ) printf %s :freecad: ;;
  Freeform ) printf %s :freeform: ;;
  Freenet ) printf %s :freenet: ;;
  FreeTube ) printf %s :freetube: ;;
  FSNotes ) printf %s :fsnotes: ;;
  Fusion ) printf %s :fusion: ;;
  Games ) printf %s :games: ;;
  'System Preferences'|'System Settings'|'系统设置'|'Réglages Système'|'システム設定'|Systemeinstellungen|'System­einstellungen'|'Системні параметри'|'Системные настройки' ) printf %s :gear: ;;
  Gemini|'Google Gemini' ) printf %s :gemini: ;;
  Ghidra ) printf %s :ghidra: ;;
  Ghostty ) printf %s :ghostty: ;;
  GIMP ) printf %s :gimp: ;;
  'GitHub Desktop'|'GitHub Copilot' ) printf %s :git_hub: ;;
  GitKraken ) printf %s :gitkraken: ;;
  Godot ) printf %s :godot: ;;
  'GOG Galaxy' ) printf %s :gog_galaxy: ;;
  GoLand ) printf %s :goland: ;;
  GoodLinks ) printf %s :goodlinks: ;;
  Goodnotes ) printf %s :goodnotes: ;;
  'Google Chat' ) printf %s :google_chat: ;;
  Chromium|'Google Chrome'|'Google Chrome Canary' ) printf %s :google_chrome: ;;
  'Google Drive' ) printf %s :google_drive: ;;
  'Google Earth Pro'|'Google Earth' ) printf %s :google_earth: ;;
  'Grammarly Editor' ) printf %s :grammarly: ;;
  Granola ) printf %s :granola: ;;
  Grapher ) printf %s :grapher: ;;
  Grayjay ) printf %s :grayjay: ;;
  'Grok Bot' ) printf %s :grok_bot: ;;
  Hammerspoon ) printf %s :hammerspoon: ;;
  HandBrake ) printf %s :handbrake: ;;
  Hazel ) printf %s :hazel: ;;
  'HBO Max' ) printf %s :hbo_max: ;;
  Helium ) printf %s :helium: ;;
  Hermes|'Hermes Agent'|'Hermes Agent Desktop'|'Hermes Agent'*'' ) printf %s :hermes_agent: ;;
  'Hex Fiend' ) printf %s :hex_fiend: ;;
  Home ) printf %s :home: ;;
  'Home Assistant' ) printf %s :home_assistant: ;;
  brew-browser|WailBrew|TapHouse|Cork|Homebrew|'Brewer X'|Applite|BrewMate|Brewlet ) printf %s :homebrew: ;;
  Hyper ) printf %s :hyper: ;;
  Hyperkey ) printf %s :hyperkey: ;;
  'iA Writer' ) printf %s :ia_writer: ;;
  'Ice Cubes' ) printf %s :ice_cubes: ;;
  'IntelliJ IDEA' ) printf %s :idea: ;;
  IINA ) printf %s :iina: ;;
  'Adobe Illustrator'*''|Illustrator ) printf %s :illustrator: ;;
  'Image Playground' ) printf %s :image_playground: ;;
  ImHex ) printf %s :imhex: ;;
  'Adobe InDesign'*''|InDesign ) printf %s :indesign: ;;
  Infuse ) printf %s :infuse: ;;
  Inkdrop ) printf %s :inkdrop: ;;
  Inkscape ) printf %s :inkscape: ;;
  Insomnia ) printf %s :insomnia: ;;
  Instagram ) printf %s :instagram: ;;
  Instapaper ) printf %s :instapaper: ;;
  Instruments ) printf %s :instruments: ;;
  'Invoice Ninja'|InvoiceNinja|'Invoice Ninja'*''|invoiceninja*'' ) printf %s :invoice_ninja: ;;
  'iPhone Mirroring' ) printf %s :iphone_mirroring: ;;
  Iris ) printf %s :iris: ;;
  iTerm|iTerm2 ) printf %s :iterm: ;;
  'Product Portal'|'iZotope RX 9'|'iZotope RX 10'|'iZotope RX 11'|'iZotope RX 12'|'iZotope Ozone 9'|'iZotope Ozone 10'|'iZotope Ozone 11'|'iZotope Ozone 12' ) printf %s :izotope: ;;
  Jan ) printf %s :jan: ;;
  'Jane Reader' ) printf %s :jane_reader: ;;
  JDownloader|JDownloader2|'Uninstall JDownloader' ) printf %s :jdownloader: ;;
  'Jellyfin Media Player'|'Jellyfin Desktop' ) printf %s :jellyfin: ;;
  Jellyseer ) printf %s :jellyseer: ;;
  'JetBrains Gateway' ) printf %s :jetbrains_gateway: ;;
  'JetBrains Toolbox' ) printf %s :jetbrains_toolbox: ;;
  Jira ) printf %s :jira: ;;
  Joplin ) printf %s :joplin: ;;
  Journal ) printf %s :journal: ;;
  JuxtaText ) printf %s :juxtatext: ;;
  '카카오톡'|KakaoTalk ) printf %s :kakaotalk: ;;
  Kakoune ) printf %s :kakoune: ;;
  'Karabiner-Elements Settings'|Karabiner-Elements ) printf %s :karabiner_elements: ;;
  Karabiner-EventViewer ) printf %s :karabiner_elements_event_viewer: ;;
  KeePassXC ) printf %s :kee_pass_x_c: ;;
  KensingtonWorks|KensingtonWorks2 ) printf %s :kensington_works: ;;
  'Keyboard Maestro' ) printf %s :keyboard_maestro: ;;
  'Keychain Access' ) printf %s :keychain_access: ;;
  Keynote|'Keynote 讲演' ) printf %s :keynote: ;;
  KiCad ) printf %s :kicad: ;;
  Kiro ) printf %s :kiro: ;;
  'Kiro Crew' ) printf %s :kiro_crew: ;;
  kitty ) printf %s :kitty: ;;
  KiwiDesk ) printf %s :kiwidesk: ;;
  Kodi ) printf %s :kodi: ;;
  krita ) printf %s :krita: ;;
  'LanguageTool for Desktop' ) printf %s :languagetool_for_desktop: ;;
  Latest ) printf %s :latest: ;;
  'League of Legends' ) printf %s :league_of_legends: ;;
  legcord|Legcord ) printf %s :legcord: ;;
  LibreWolf ) printf %s :libre_wolf: ;;
  LibreOffice ) printf %s :libreoffice: ;;
  Lidarr ) printf %s :lidarr: ;;
  'Adobe Lightroom' ) printf %s :lightroom: ;;
  'Lightroom Classic' ) printf %s :lightroomclassic: ;;
  LINE ) printf %s :line: ;;
  Linear ) printf %s :linear: ;;
  'Little Snitch'|'Little Snitch Network Monitor' ) printf %s :little_snitch: ;;
  'Little Snitch Mini'*'' ) printf %s :little_snitch_mini: ;;
  'LM Studio' ) printf %s :lm_studio: ;;
  LobeHub ) printf %s :lobehub: ;;
  LocalSend ) printf %s :localsend: ;;
  'Logic Pro' ) printf %s :logicpro: ;;
  Logseq ) printf %s :logseq: ;;
  LuLu ) printf %s :lulu: ;;
  Maccy ) printf %s :maccy_clip: ;;
  MacForge ) printf %s :macforge: ;;
  MacPass ) printf %s :macpass: ;;
  macshot|macshot.app|MacShot ) printf %s :macshot: ;;
  Mactracker ) printf %s :mactracker: ;;
  Magnifier ) printf %s :magnifier: ;;
  'Canary Mail'|HEY|Mail|Mailspring|MailMate|Superhuman|Spark|'Spark Mail'|'邮件'|'メール'|'Пошта'|'Почта' ) printf %s :mail: ;;
  MakeMKV ) printf %s :makemkv: ;;
  MAMP|'MAMP PRO' ) printf %s :mamp: ;;
  Maps|'Google Maps'|'マップ'|Karten|'Карти'|'Карты' ) printf %s :maps: ;;
  'Marked 2' ) printf %s :marked_2: ;;
  MarkText|MarkText+ ) printf %s :marktext: ;;
  Marta ) printf %s :marta: ;;
  Matlab|MATLAB|MATLABWindow|MATLAB_R2024b|MATLAB_R2024a|MATLAB_R2023b|MATLAB_R2023a|MATLAB_R2022b|MATLAB_R2022a|MATLAB_R2021b|MATLAB_R2021a ) printf %s :matlab: ;;
  Mattermost ) printf %s :mattermost: ;;
  MediaInfo ) printf %s :mediainfo: ;;
  'Google Meet' ) printf %s :meet: ;;
  MEGA ) printf %s :mega: ;;
  Messages|'信息'|Nachrichten|'メッセージ'|'Повідомлення'|'Сообщения' ) printf %s :messages: ;;
  Messenger ) printf %s :messenger: ;;
  'Microsoft Edge' ) printf %s :microsoft_edge: ;;
  'Microsoft Excel' ) printf %s :microsoft_excel: ;;
  'Microsoft Outlook' ) printf %s :microsoft_outlook: ;;
  'Microsoft PowerPoint' ) printf %s :microsoft_power_point: ;;
  'Microsoft Remote Desktop' ) printf %s :microsoft_remote_desktop: ;;
  'Microsoft Teams'|'Microsoft Teams (work or school)' ) printf %s :microsoft_teams: ;;
  'Microsoft Word' ) printf %s :microsoft_word: ;;
  Migaku ) printf %s :migaku: ;;
  Mimestream ) printf %s :mimestream: ;;
  Min ) printf %s :min_browser: ;;
  Minecraft|'Minecraft Launcher' ) printf %s :minecraft: ;;
  Miro ) printf %s :miro: ;;
  Mole ) printf %s :mole: ;;
  'MongoDB Compass'*'' ) printf %s :mongodb: ;;
  Moonlight ) printf %s :moonlight: ;;
  Motrix ) printf %s :motrix: ;;
  'Movist Pro' ) printf %s :movist_pro: ;;
  Mp3tag ) printf %s :mp3tag: ;;
  mpv ) printf %s :mpv: ;;
  MQTTX ) printf %s :mqttx: ;;
  MTGA ) printf %s :mtga: ;;
  'Mullvad Browser' ) printf %s :mullvad_browser: ;;
  'Mullvad VPN' ) printf %s :mullvad_vpn: ;;
  Muse ) printf %s :muse: ;;
  MuseHub ) printf %s :musehub: ;;
  MuseScore|'MuseScore 4'|'MuseScore Studio' ) printf %s :musescore: ;;
  Music|'音乐'|Musique|'ミュージック'|Musik|Chromatix|'Музика'|'Музыка' ) printf %s :music: ;;
  Muxy ) printf %s :muxy: ;;
  'Native Access' ) printf %s :native_instruments: ;;
  'Navicat Premium' ) printf %s :navicat: ;;
  NeoHtop ) printf %s :neohtop: ;;
  Neovide|neovide ) printf %s :neovide: ;;
  Neovim|neovim|nvim ) printf %s :neovim: ;;
  '网易云音乐'|NetEaseMusic ) printf %s :netease_music: ;;
  Netflix ) printf %s :netflix: ;;
  NetNewsWire ) printf %s :netnewswire: ;;
  'MA 1 - Automatic Monitor Alignment' ) printf %s :neumann: ;;
  News ) printf %s :news: ;;
  Nextcloud ) printf %s :nextcloud: ;;
  Nicotine+ ) printf %s :nicotine_plus: ;;
  'Nimble Commander'|NimbleCommander-Unsigned ) printf %s :nimble_commander: ;;
  Noodl|'Noodl Editor' ) printf %s :noodl: ;;
  NordVPN ) printf %s :nord_vpn: ;;
  Notability ) printf %s :notability: ;;
  Notes|'备忘录'|'メモ'|Notizen|'Нотатки'|'Заметки' ) printf %s :notes: ;;
  Notion ) printf %s :notion: ;;
  'Notion Mail' ) printf %s :notion_mail: ;;
  Nova ) printf %s :nova: ;;
  Numbers|'Numbers 表格' ) printf %s :numbers: ;;
  nvALT ) printf %s :nvalt: ;;
  'Nvidia GeForce Now'|GeForceNOW ) printf %s :nvidia_geforce_now: ;;
  Nzbget ) printf %s :nzbget: ;;
  Obsidian ) printf %s :obsidian: ;;
  OBS ) printf %s :obsstudio: ;;
  Ollama ) printf %s :ollama: ;;
  OmniDiskSweeper ) printf %s :omni_disk_sweeper: ;;
  OmniFocus ) printf %s :omni_focus: ;;
  OmniRoute ) printf %s :omniroute: ;;
  1Password ) printf %s :one_password: ;;
  OneDrive ) printf %s :onedrive: ;;
  ONLYOFFICE ) printf %s :onlyoffice: ;;
  OpenKnowledge ) printf %s :open_knowledge: ;;
  'Open Video Downloader' ) printf %s :open_video_downloader: ;;
  ChatGPT|'ChatGPT Classic' ) printf %s :openai: ;;
  'OpenAI Translator' ) printf %s :openai_translator: ;;
  OpenChamber ) printf %s :openchamber: ;;
  OpenClaw ) printf %s :openclaw: ;;
  opencode|OpenCode ) printf %s :opencode: ;;
  OpenEmu ) printf %s :openemu: ;;
  'OpenVPN Connect' ) printf %s :openvpn_connect: ;;
  Opera ) printf %s :opera: ;;
  OrbStack ) printf %s :orbstack: ;;
  OrcaSlicer ) printf %s :orcaslicer: ;;
  Orion|'Orion RC' ) printf %s :orion: ;;
  Osaurus ) printf %s :osaurus: ;;
  Otty ) printf %s :otty: ;;
  Overcast ) printf %s :overcast: ;;
  Overleaf|ShareLaTeX ) printf %s :overleaf: ;;
  Overseer|Seer ) printf %s :overseer: ;;
  Pages|'Pages 文稿' ) printf %s :pages: ;;
  'Parallels Desktop' ) printf %s :parallels: ;;
  Parcel ) printf %s :parcel: ;;
  Parsec ) printf %s :parsec: ;;
  Paseo ) printf %s :paseo: ;;
  Passepartout ) printf %s :passepartout: ;;
  'Password Depot' ) printf %s :password_depot: ;;
  AutoFillPanelService|coreautha|Passwords|'Passwörter'|'Паролі'|'Пароли' ) printf %s :passwords: ;;
  PasteBar ) printf %s :pastebar: ;;
  PCSX2 ) printf %s :pcsx2: ;;
  'PDF Expert' ) printf %s :pdf_expert: ;;
  Pearcleaner ) printf %s :pearcleaner: ;;
  'Permute 3'|'Permute 4' ) printf %s :permute: ;;
  Perplexity|'Perplexity AI' ) printf %s :perplexity: ;;
  'pgAdmin 4' ) printf %s :pgadmin: ;;
  'Phoenix Slides' ) printf %s :phoenix_slides: ;;
  Phone ) printf %s :phone: ;;
  Photos|Fotos|'Фото' ) printf %s :photos: ;;
  'Adobe Photoshop'*'' ) printf %s :photoshop: ;;
  PhpStorm ) printf %s :php_storm: ;;
  'Pi-hole Remote' ) printf %s :pihole: ;;
  Pine ) printf %s :pine: ;;
  Pinta ) printf %s :pinta: ;;
  Pixcall ) printf %s :pixcall: ;;
  'Pixelmator Pro' ) printf %s :pixelmator_pro: ;;
  PixiEditor ) printf %s :pixieditor: ;;
  Play ) printf %s :play: ;;
  Plex ) printf %s :plex: ;;
  Plexamp ) printf %s :plexamp: ;;
  Plezy ) printf %s :plezy: ;;
  Podcasts|'播客'|'Подкасти'|'Подкасты' ) printf %s :podcasts: ;;
  'PomoDone App' ) printf %s :pomodone: ;;
  Postman ) printf %s :postman: ;;
  Premiere|'Adobe Premiere'|'Adobe Premiere Pro 2024' ) printf %s :premiere: ;;
  Preview|'预览'|Skim|zathura|'Aperçu'|'プレビュー'|Vorschau|'Оглядач'|'Просмотр' ) printf %s :preview: ;;
  'Print Center'|Druckzentrale ) printf %s :print_center: ;;
  'Pro Tools' ) printf %s :pro_tools: ;;
  'Problem Reporter' ) printf %s :problem_reporter: ;;
  Authenticator|'Proton Authenticator' ) printf %s :proton_authenticator: ;;
  'Proton Drive' ) printf %s :proton_drive: ;;
  'Proton Mail'|'Proton Mail Bridge' ) printf %s :proton_mail: ;;
  'Proton Meet' ) printf %s :proton_meet: ;;
  'Proton Pass'|'Proton Pass for Safari' ) printf %s :proton_pass: ;;
  'Proton VPN'|ProtonVPN ) printf %s :proton_vpn: ;;
  Prowlarr ) printf %s :prowlarr: ;;
  Proxyman ) printf %s :proxyman: ;;
  PrusaSlicer|SuperSlicer ) printf %s :prusaslicer: ;;
  'PS Remote Play' ) printf %s :ps_remote_play: ;;
  PureMac ) printf %s :puremac: ;;
  PyCharm ) printf %s :pycharm: ;;
  qBittorrent ) printf %s :qbittorrent: ;;
  QBZ ) printf %s :qbz: ;;
  QGIS ) printf %s :qgis: ;;
  QLMarkdown ) printf %s :qlmarkdown: ;;
  Qobuz ) printf %s :qobuz: ;;
  QQ ) printf %s :qq: ;;
  'QQ音乐'|QQMusic ) printf %s :qqmusic: ;;
  'Quantumult X' ) printf %s :quantumult_x: ;;
  Quark|'夸克' ) printf %s :quark: ;;
  'QuickTime Player' ) printf %s :quicktime: ;;
  Quip ) printf %s :quip: ;;
  qutebrowser ) printf %s :qute_browser: ;;
  Radarr ) printf %s :radarr: ;;
  Raindrop.io ) printf %s :raindrop_io: ;;
  'Raspberry Pi Imager'|'Raspberry Pi Connect' ) printf %s :raspberry_pi: ;;
  Raycast|'Raycast Beta' ) printf %s :raycast: ;;
  rclone|Rclone|'Rclone UI' ) printf %s :rclone: ;;
  REAPER ) printf %s :reaper: ;;
  Reeder ) printf %s :reeder5: ;;
  rekordbox ) printf %s :rekordbox: ;;
  'Remind Faster' ) printf %s :remind_me_faster: ;;
  Reminders|'提醒事项'|Rappels|'リマインダー'|Erinnerungen|'Нагадування'|'Напоминания' ) printf %s :reminders: ;;
  RenameMyTVSeries|'Rename My TV Series' ) printf %s :rename_my_tv_series: ;;
  Replit ) printf %s :replit: ;;
  'Repo Prompt' ) printf %s :repo_prompt: ;;
  'Resilio Sync' ) printf %s :resilio_sync: ;;
  Rider|'JetBrains Rider' ) printf %s :rider: ;;
  Rio ) printf %s :rio: ;;
  Roblox ) printf %s :roblox: ;;
  'Royal TSX' ) printf %s :royaltsx: ;;
  RStudio ) printf %s :rstudio: ;;
  RsyncUI ) printf %s :rsyncui: ;;
  ruffle|Ruffle ) printf %s :ruffle: ;;
  RustDesk ) printf %s :rustdesk: ;;
  SABnzbd ) printf %s :sabnzbd: ;;
  Safari|'Safari浏览器'|'Safari Technology Preview' ) printf %s :safari: ;;
  Screencap ) printf %s :screencap: ;;
  Scribus ) printf %s :scribus: ;;
  'Script Debugger' ) printf %s :script_debugger: ;;
  'Script Editor' ) printf %s :script_editor: ;;
  Seafile ) printf %s :seafile: ;;
  Search ) printf %s :search: ;;
  Secretive|Secretive.app ) printf %s :secretive: ;;
  'Sequel Ace' ) printf %s :sequel_ace: ;;
  'Sequel Pro' ) printf %s :sequel_pro: ;;
  Session ) printf %s :session: ;;
  Setapp ) printf %s :setapp: ;;
  'SF Symbols'|'SF Symbole'|SF-Symbole|'SF Symbols Beta' ) printf %s :sf_symbols: ;;
  Shapr3D ) printf %s :shapr3d: ;;
  Shortcuts|'Команди'|'Команды' ) printf %s :shortcuts: ;;
  Sibelius ) printf %s :sibelius: ;;
  Signal ) printf %s :signal: ;;
  'Silveran Reader' ) printf %s :silveran_reader: ;;
  sioyek ) printf %s :sioyek: ;;
  Siri ) printf %s :siri: ;;
  Sketch ) printf %s :sketch: ;;
  Skype ) printf %s :skype: ;;
  Slack ) printf %s :slack: ;;
  SmartGit ) printf %s :smartgit: ;;
  SmoothCSV ) printf %s :smoothcsv: ;;
  SnapGene ) printf %s :snapgene: ;;
  SnippetsLab ) printf %s :snippetslab: ;;
  solidtime ) printf %s :solidtime: ;;
  Sonarr ) printf %s :sonarr: ;;
  SourceGit ) printf %s :sourcegit: ;;
  Sourcetree ) printf %s :sourcetree: ;;
  'Spark Desktop' ) printf %s :spark: ;;
  Sparkle ) printf %s :sparkle: ;;
  Spotify ) printf %s :spotify: ;;
  Spotlight ) printf %s :spotlight: ;;
  StarUML ) printf %s :staruml: ;;
  Steam|'Steam Helper' ) printf %s :steam: ;;
  Stickies ) printf %s :stickies: ;;
  Stocks ) printf %s :stocks: ;;
  Stremio ) printf %s :stremio: ;;
  'Studio 3T' ) printf %s :studio_3t: ;;
  'Sublime Merge' ) printf %s :sublime_merge: ;;
  'Sublime Text' ) printf %s :sublime_text: ;;
  'Summoners War' ) printf %s :summoners_war: ;;
  'Super Productivity'|superProductivity ) printf %s :super_productivity: ;;
  Surfshark ) printf %s :surfshark: ;;
  'Swift Playground' ) printf %s :swift_playground: ;;
  Synergy ) printf %s :synergy: ;;
  'System Information'|'System Profiler' ) printf %s :system_information: ;;
  'T3 Code'|'T3 Code (Alpha)' ) printf %s :t3_code: ;;
  'T3 Chat' ) printf %s :t3chat: ;;
  Tabby ) printf %s :tabby: ;;
  TablePlus ) printf %s :tableplus: ;;
  Tailscale ) printf %s :tailscale: ;;
  Tana ) printf %s :tana: ;;
  Tautulli ) printf %s :tautulli: ;;
  'TeamSpeak 3' ) printf %s :team_speak: ;;
  TeamViewer ) printf %s :teamviewer: ;;
  Telegram ) printf %s :telegram: ;;
  Terminal|'终端'|'ターミナル'|'Термінал'|'Терминал' ) printf %s :terminal: ;;
  Termius ) printf %s :termius: ;;
  TestFlight ) printf %s :testflight: ;;
  Typora ) printf %s :text: ;;
  TextEdit ) printf %s :textedit: ;;
  'The Sims 3'|'The Sims 4' ) printf %s :the_sims: ;;
  'Microsoft To Do'|Things ) printf %s :things: ;;
  Threema*'' ) printf %s :threema: ;;
  Thunderbird|'Thunderbird Daily' ) printf %s :thunderbird: ;;
  'TI Connect CE' ) printf %s :ti_connect_ce: ;;
  TickTick ) printf %s :tick_tick: ;;
  TIDAL ) printf %s :tidal: ;;
  TigerVNC ) printf %s :tigervnc: ;;
  'Time Machine'|TimeMachineEditor|TheTimeMachineMechanic ) printf %s :time_machine: ;;
  Timery ) printf %s :timery: ;;
  Timing ) printf %s :timingapp: ;;
  'Tiny RDM' ) printf %s :tinyrdm: ;;
  Tips ) printf %s :tips: ;;
  Todoist ) printf %s :todoist: ;;
  'Toggl Track' ) printf %s :toggl_track: ;;
  'Tor Browser' ) printf %s :tor_browser: ;;
  Tot ) printf %s :tot: ;;
  Tower ) printf %s :tower: ;;
  TradingView ) printf %s :trading_view: ;;
  Transmission ) printf %s :transmission: ;;
  Transmit ) printf %s :transmit: ;;
  Trello ) printf %s :trello: ;;
  Tuna|'Tuna (beta)' ) printf %s :tuna: ;;
  Tuple ) printf %s :tuple: ;;
  Twingate ) printf %s :twingate: ;;
  Tweetbot|Twitter ) printf %s :twitter: ;;
  'UGREEN NAS' ) printf %s :ugreen-nas: ;;
  Unity|'Unity Hub' ) printf %s :unity: ;;
  Usenapp ) printf %s :usenapp: ;;
  UTM ) printf %s :utm: ;;
  VeraCrypt ) printf %s :veracrypt: ;;
  Vesktop ) printf %s :vesktop: ;;
  Viber ) printf %s :viber: ;;
  MacVim|Vim|VimR ) printf %s :vim: ;;
  VirtualBox ) printf %s :virtualbox: ;;
  'Visual Studio' ) printf %s :visual_studio: ;;
  Vivaldi ) printf %s :vivaldi: ;;
  VLC ) printf %s :vlc: ;;
  'VMware Fusion' ) printf %s :vmware_fusion: ;;
  'Voice Memos' ) printf %s :voice_memos: ;;
  Vorta ) printf %s :vorta: ;;
  VSCodium ) printf %s :vscodium: ;;
  Warp ) printf %s :warp: ;;
  Wave ) printf %s :waveterm: ;;
  Waydir ) printf %s :waydir: ;;
  Weather|Wetter|'Погода' ) printf %s :weather: ;;
  WebStorm ) printf %s :web_storm: ;;
  WebTorrent ) printf %s :webtorrent: ;;
  'Webull Desktop' ) printf %s :webull: ;;
  '微信'|WeChat ) printf %s :wechat: ;;
  '企业微信'|WeCom ) printf %s :wecom: ;;
  WeTransfer ) printf %s :wetransfer: ;;
  WezTerm|wezterm-gui ) printf %s :wezterm: ;;
  WhatCable ) printf %s :whatcable: ;;
  WhatsApp|'‎WhatsApp' ) printf %s :whats_app: ;;
  'Windows App' ) printf %s :windows_app: ;;
  WireGuard ) printf %s :wireguard: ;;
  Wireshark ) printf %s :wireshark: ;;
  'Wispr Flow' ) printf %s :wispr_flow: ;;
  xemu ) printf %s :xbox: ;;
  Xcode ) printf %s :xcode: ;;
  XMind ) printf %s :xmind: ;;
  Yaak ) printf %s :yaak: ;;
  'Yandex Browser'|'Yandex Browser'|Yandex ) printf %s :yandex_browser: ;;
  'Yandex Music' ) printf %s :yandex_music: ;;
  Yazi|yazi ) printf %s :yazi: ;;
  YouTube ) printf %s :youtube: ;;
  'YouTube Music' ) printf %s :youtube_music: ;;
  'Yubico Authenticator'|'YubiKey Manager' ) printf %s :yubico: ;;
  Yuque|'语雀' ) printf %s :yuque: ;;
  Z-Library ) printf %s :z_library: ;;
  Zed|'Zed Preview' ) printf %s :zed: ;;
  Zen|'Zen Browser'|Twilight ) printf %s :zen_browser: ;;
  Zeplin ) printf %s :zeplin: ;;
  zoom.us|Zoom ) printf %s :zoom: ;;
  Zotero ) printf %s :zotero: ;;
  Zulip ) printf %s :zulip: ;;
  *) printf %s ':default:' ;;
esac
